language: csharp
solution: IdentityMicroservice/IdentityMicroservice.sln
mono: none
dist: xenial
sudo: required
dotnet: 2.0.0
script:
 - dotnet restore IdentityMicroservice/IdentityMicroservice.sln
 - dotnet build IdentityMicroservice/IdentityMicroservice.sln
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1